version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - ls -lrt
      - docker --version
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t hello-repository2:latest .
      - docker tag catnip:latest 580338969199.dkr.ecr.ap-south-1.amazonaws.com/hello-repository2    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 580338969199.dkr.ecr.ap-south-1.amazonaws.com/hello-repository2
artifacts:
  files:
    - '**/*'
